services:
  - type: web
    name: birbal-backend
    env: node
    buildCommand: npm install
    startCommand: node main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000